# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kty < Formula
  desc "Terminal for kubernetes"
  homepage "https://github.com/grampelberg/kty"
  url "https://github.com/grampelberg/kty/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "050c8b0df88f65e1a06863bea99495b77bf2045829825e7e130756f1828c6aa6"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.1/kty-0.3.1-darwin-arm64.tar.gz"
      sha256 "2fef571f8b14427dddcaf204c5f7c8435b45a25b714701867356e1a55821ce40"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.1/kty-0.3.1-linux-amd64.tar.gz"
      sha256 "09fcc64cebf72fa29cebb0eed26994d9139f366cd93d2ee7183ac69237508860"
    end

    on_arm do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.1/kty-0.3.1-linux-arm64.tar.gz"
      sha256 "03d26bf41e1d01b24120757d2e8aeac4b15149f21f2119db5898f9c52a429b9d"
    end
  end

  def install
    bin.install "kty" => "kty"
  end

  test do
    assert_match("kty", shell_output("kty"))
  end
end
