# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Kty < Formula
  desc "Terminal for kubernetes"
  homepage "https://github.com/grampelberg/kty"
  url "https://github.com/grampelberg/kty/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "8293f62b8c008089aa56b319dbb702edb960aa73365eca8dcb53279880d29b47"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.0/kty-0.3.0-darwin-arm64.tar.gz"
      sha256 "843819ac621d73f1f98aa75adfd6eb328745009ff27d9fc2eceedb29809b1280"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.0/kty-0.3.0-linux-amd64.tar.gz"
      sha256 "3b87e44cf1e9950e54ff76bef127c7e37d2cd37f9b560a32309bbcb7a68b08e8"
    end

    on_arm do
      url "https://github.com/grampelberg/kty/releases/download/v0.3.0/kty-0.3.0-linux-arm64.tar.gz"
      sha256 "a2856dd547f9b9b5685683a645e2a5e5e59ce158d05ac204b01053248c174d5f"
    end
  end

  def install
    bin.install "kty" => "kty"
  end

  test do
    assert_match("kty", shell_output("kty"))
  end
end
